version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  caddy: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    depends_on:
      - db
      - redis
    env_file: .env
    command: /gunicorn.sh

  db:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  caddy:
    build:
      context: .
      dockerfile: ./compose/caddy/Dockerfile
    depends_on:
      - django
    volumes:
      - caddy:/root/.caddy
    env_file: .env
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  redis:
    image: redis:alpine
    restart: always