# Generated by Django 2.0 on 2017-12-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0002_auto_20171207_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatstate',
            name='state',
            field=models.CharField(choices=[('game', 'in main menu'), ('menu', 'in game')], max_length=20),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
