# Generated by Django 2.0 on 2017-12-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0003_auto_20171207_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatstate',
            name='state',
            field=models.CharField(choices=[('menu', 'in main menu'), ('game', 'in game')], max_length=20),
        ),
    ]
