# Generated by Django 2.0.4 on 2018-05-03 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('source', models.CharField(choices=[('u', 'user'), ('g', 'game')], default='g', max_length=1)),
                ('text', models.TextField(verbose_name='text')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('status', models.CharField(choices=[('a', 'active'), ('f', 'finished')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SessionCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_games', to='game.Character', verbose_name='character')),
                ('current_moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moment_characters', to='game.Moment', verbose_name='current moment')),
                ('current_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_characters', to='game.Scene', verbose_name='current scene')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='play.Session', verbose_name='session')),
            ],
        ),
        migrations.CreateModel(
            name='SessionProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('current_value', models.CharField(blank=True, max_length=100, verbose_name='current value')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='play.SessionCharacter', verbose_name='character')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_games', to='game.Property', verbose_name='property')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='play.Session', verbose_name='session')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='active_character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_sessions', to='play.SessionCharacter', verbose_name='active character'),
        ),
        migrations.AddField(
            model_name='session',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_sessions', to='game.Game', verbose_name='game'),
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_sessions', to='telegrambot.User', verbose_name='user'),
        ),
        migrations.AddField(
            model_name='gamelog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamelogs', to='play.Session', verbose_name='session'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionproperty',
            unique_together={('session', 'property')},
        ),
        migrations.AlterUniqueTogether(
            name='sessioncharacter',
            unique_together={('character', 'session')},
        ),
    ]
